name: Clone

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_TOKEN}
          echo ${GITHUB_ACTOR}
      - run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          echo "branch=${echo $GITHUB_REF | cut -f 2 -d '@'}" >> $GITHUB_ENV
          git push origin HEAD:${env.branch}; \
